In [1]:
from modules.wire import INR
import torch
from math import sqrt

In [2]:
def make_model(hidden_layers:int):
    return INR(
        in_features=2,
        hidden_features=256*sqrt(2),
        hidden_layers=hidden_layers,
        out_features=3,
        scale=2.,
        first_omega_0=15.,
        hidden_omega_0=15.,
    )

models = [make_model(i) for i in range(1, 7)]

In [3]:
inputs_0 = torch.rand((5, 2))
inputs_1 = -1 + 2* torch.rand((5, 2))

In [4]:
outs_0 = [model(inputs_0) for model in models]
outs_1 = [model(inputs_1) for model in models]

In [5]:
outs_0

[tensor([[ 1369.0179, -1392.2070, -5305.4146],
         [ 7220.6382,   148.1748, -4163.9907],
         [   51.3730,   328.8542,   782.0274],
         [ -344.1565,  9047.9756,  4680.9229],
         [-1987.6875,   468.9665,  1058.0876]], grad_fn=<SelectBackward0>),
 tensor([[-0.0289,  0.0615, -0.0363],
         [-0.0289,  0.0615, -0.0363],
         [-0.0289,  0.0615, -0.0363],
         [-0.0289,  0.0615, -0.0363],
         [-0.0289,  0.0615, -0.0363]], grad_fn=<SelectBackward0>),
 tensor([[ 0.3838,  0.4860, -0.9336],
         [ 0.3838,  0.4860, -0.9336],
         [ 0.3838,  0.4860, -0.9336],
         [ 0.3838,  0.4860, -0.9336],
         [ 0.3838,  0.4860, -0.9336]], grad_fn=<SelectBackward0>),
 tensor([[ 35207.7812,  -2118.9380, -12696.4707],
         [ 35207.7812,  -2118.9380, -12696.4707],
         [ 35207.7812,  -2118.9380, -12696.4707],
         [ 35207.7812,  -2118.9380, -12696.4707],
         [ 35207.7812,  -2118.9380, -12696.4707]], grad_fn=<SelectBackward0>),
 tensor([[-0.0450, 

In [6]:
outs_1

[tensor([[ 4160.1050,  3033.5000, -1302.2251],
         [  430.3455, -2978.3364,  -631.3229],
         [ -883.6915,  1536.2260, -1748.4408],
         [ -761.0325, -1068.6208,   225.1847],
         [ -845.4832,  1007.1001,   674.5405]], grad_fn=<SelectBackward0>),
 tensor([[-0.0289,  0.0615, -0.0363],
         [-0.0289,  0.0615, -0.0363],
         [-0.0289,  0.0615, -0.0363],
         [-0.0289,  0.0615, -0.0363],
         [-0.0289,  0.0615, -0.0363]], grad_fn=<SelectBackward0>),
 tensor([[ 0.3838,  0.4860, -0.9336],
         [ 0.3838,  0.4860, -0.9336],
         [ 0.3838,  0.4860, -0.9336],
         [ 0.3838,  0.4860, -0.9336],
         [ 0.3838,  0.4860, -0.9336]], grad_fn=<SelectBackward0>),
 tensor([[ 35207.7812,  -2118.9380, -12696.4707],
         [ 35207.7812,  -2118.9380, -12696.4707],
         [ 35207.7812,  -2118.9380, -12696.4707],
         [ 35207.7812,  -2118.9380, -12696.4707],
         [ 35207.7812,  -2118.9380, -12696.4707]], grad_fn=<SelectBackward0>),
 tensor([[-0.0450, 

In [7]:
outs_0[0].dtype

torch.float32

In [8]:
models[0]

INR(
  (net): Sequential(
    (0): ComplexGaborLayer(
      (linear): Linear(in_features=2, out_features=256, bias=True)
    )
    (1): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (2): Linear(in_features=256, out_features=3, bias=True)
  )
)

In [9]:
models[3]

INR(
  (net): Sequential(
    (0): ComplexGaborLayer(
      (linear): Linear(in_features=2, out_features=256, bias=True)
    )
    (1): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (2): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (3): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (4): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (5): Linear(in_features=256, out_features=3, bias=True)
  )
)

In [10]:
layers = list(models[-1].net)

In [11]:
h = inputs_0
outs = [h]
for layer in layers:
    h = layer(h)
    print(h.norm(dim=-1))
    outs.append(h)

tensor([ 9.4884,  9.4245,  9.8296, 10.6589, 10.7044], grad_fn=<NormBackward1>)
tensor([39974.2891, 51535.1328, 29336.9883, 59940.5625, 25752.6152],
       grad_fn=<NormBackward1>)
tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>)
tensor([20.3681, 20.3681, 20.3681, 20.3681, 20.3681], grad_fn=<NormBackward1>)
tensor([2631823.2500, 2631823.2500, 2631823.2500, 2631823.2500, 2631823.2500],
       grad_fn=<NormBackward1>)
tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>)
tensor([18.9483, 18.9483, 18.9483, 18.9483, 18.9483], grad_fn=<NormBackward1>)
tensor([1.7228, 1.7228, 1.7228, 1.7228, 1.7228], grad_fn=<NormBackward1>)


In [12]:
outs[3]

tensor([[-0.-0.j, 0.-0.j, -0.+0.j,  ..., 0.+0.j, 0.-0.j, -0.-0.j],
        [0.-0.j, 0.+0.j, 0.-0.j,  ..., 0.-0.j, 0.+0.j, 0.+0.j],
        [-0.+0.j, -0.+0.j, 0.+0.j,  ..., 0.-0.j, 0.-0.j, -0.-0.j],
        [0.+0.j, -0.+0.j, 0.+0.j,  ..., -0.+0.j, -0.+0.j, 0.+0.j],
        [-0.+0.j, -0.-0.j, 0.+0.j,  ..., 0.-0.j, -0.+0.j, -0.+0.j]],
       grad_fn=<ExpBackward0>)

In [13]:
layers[2](outs[2])

tensor([[-0.-0.j, 0.-0.j, -0.+0.j,  ..., 0.+0.j, 0.-0.j, -0.-0.j],
        [0.-0.j, 0.+0.j, 0.-0.j,  ..., 0.-0.j, 0.+0.j, 0.+0.j],
        [-0.+0.j, -0.+0.j, 0.+0.j,  ..., 0.-0.j, 0.-0.j, -0.-0.j],
        [0.+0.j, -0.+0.j, 0.+0.j,  ..., -0.+0.j, -0.+0.j, 0.+0.j],
        [-0.+0.j, -0.-0.j, 0.+0.j,  ..., 0.-0.j, -0.+0.j, -0.+0.j]],
       grad_fn=<ExpBackward0>)

In [14]:
layers[2].linear.weight

Parameter containing:
tensor([[-0.0045-0.0383j,  0.0505+0.0183j,  0.0030-0.0616j,  ...,
          0.0278-0.0152j,  0.0293-0.0068j, -0.0018+0.0379j],
        [ 0.0245+0.0266j,  0.0600+0.0595j,  0.0567+0.0030j,  ...,
          0.0048+0.0582j, -0.0133+0.0408j,  0.0036+0.0065j],
        [ 0.0334-0.0542j, -0.0278-0.0016j,  0.0008-0.0450j,  ...,
         -0.0495-0.0065j, -0.0602+0.0311j, -0.0573+0.0377j],
        ...,
        [-0.0031-0.0057j,  0.0393-0.0115j, -0.0058-0.0507j,  ...,
         -0.0340-0.0529j,  0.0594+0.0207j, -0.0019+0.0452j],
        [-0.0452-0.0512j,  0.0314+0.0229j,  0.0037+0.0407j,  ...,
          0.0426-0.0063j, -0.0342-0.0331j,  0.0250+0.0242j],
        [ 0.0344-0.0345j, -0.0335-0.0140j,  0.0248+0.0024j,  ...,
         -0.0616+0.0046j, -0.0483-0.0050j, -0.0022+0.0001j]],
       requires_grad=True)

In [15]:
pre_activation = outs[2]@layers[2].linear.weight.T + layers[2].linear.bias
pre_activation.real.norm(dim=-1), pre_activation.imag.norm(dim=-1)

(tensor([22851.9707, 29239.6270, 17242.8457, 32803.6367, 15663.3164],
        grad_fn=<NormBackward1>),
 tensor([22574.8281, 29177.6465, 16208.7930, 33671.6250, 14948.4541],
        grad_fn=<NormBackward1>))

In [16]:
freq = 1j * layers[2].omega_0*pre_activation
print(freq.real.norm(dim=-1), freq.imag.norm(dim=-1))
freq = torch.exp(freq)
print(freq.real.norm(dim=-1), freq.imag.norm(dim=-1))

tensor([338622.3438, 437664.8438, 243131.8594, 505074.3750, 224226.7656],
       grad_fn=<NormBackward1>) tensor([342779.5625, 438594.3438, 258642.7031, 492054.5625, 234949.7500],
       grad_fn=<NormBackward1>)
tensor([inf, inf, inf, inf, inf], grad_fn=<NormBackward1>) tensor([inf, inf, inf, inf, inf], grad_fn=<NormBackward1>)


In [17]:
gauss = layers[2].scale_0*pre_activation
print(gauss.real.norm(dim=-1), gauss.imag.norm(dim=-1))
gauss = torch.exp(-torch.square(torch.abs(gauss)))
print(gauss.norm(dim=-1))

tensor([45703.9414, 58479.2539, 34485.6914, 65607.2734, 31326.6328],
       grad_fn=<NormBackward1>) tensor([45149.6562, 58355.2930, 32417.5859, 67343.2500, 29896.9082],
       grad_fn=<NormBackward1>)
tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>)


In [18]:
gauss * freq

tensor([[nan+nanj, 0.+0.j, -0.+0.j,  ..., 0.+0.j, 0.+0.j, 0.-0.j],
        [0.+0.j, 0.+0.j, 0.+0.j,  ..., 0.+0.j, nan+nanj, 0.+0.j],
        [-0.+0.j, -0.+0.j, nan+nanj,  ..., 0.+0.j, 0.+0.j, 0.-0.j],
        [0.+0.j, nan+nanj, nan+nanj,  ..., -0.+0.j, nan+nanj, nan+nanj],
        [nan+nanj, nan+nanj, nan+nanj,  ..., 0.+0.j, -0.+0.j, -0.+0.j]],
       grad_fn=<MulBackward0>)

In [19]:
their_way = 1j * layers[2].omega_0*pre_activation - torch.square(torch.abs(layers[2].scale_0*pre_activation))
print(their_way.real.norm(dim=-1), their_way.imag.norm(dim=-1))
their_way = torch.exp(their_way)
print(their_way.real.norm(dim=-1), their_way.imag.norm(dim=-1))

tensor([3.6190e+08, 5.0717e+08, 1.7914e+08, 7.8089e+08, 1.5950e+08],
       grad_fn=<NormBackward1>) tensor([342779.5625, 438594.3438, 258642.7031, 492054.5625, 234949.7500],
       grad_fn=<NormBackward1>)
tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>) tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>)
