In [1]:
from modules.wire import INR
import torch
from math import sqrt

In [2]:
def make_model(hidden_layers:int):
    return INR(
        in_features=2,
        hidden_features=256*sqrt(2),
        hidden_layers=hidden_layers,
        out_features=3,
        scale=2.,
        first_omega_0=15.,
        hidden_omega_0=15.,
    )

models = [make_model(i) for i in range(1, 7)]

In [3]:
inputs_0 = torch.rand((5, 2))
inputs_1 = -1 + 2* torch.rand((5, 2))

In [4]:
outs_0 = [model(inputs_0) for model in models]
outs_1 = [model(inputs_1) for model in models]

In [5]:
outs_0

[tensor([[ 5680.0869,  4140.1680, -1763.1952],
         [-3334.3987, -1531.8690,  -110.1648],
         [  -73.7948,   208.6802,  1565.0809],
         [  -84.8828,    13.1362,   -64.1247],
         [  -39.0875,   124.7852,   544.1834]], grad_fn=<SelectBackward0>),
 tensor([[ 0.0457, -0.0499, -0.0106],
         [ 0.0457, -0.0499, -0.0106],
         [ 0.0457, -0.0499, -0.0106],
         [ 0.0457, -0.0499, -0.0106],
         [ 0.0457, -0.0499, -0.0106]], grad_fn=<SelectBackward0>),
 tensor([[ 0.9823, -1.1624,  0.4793],
         [ 0.9823, -1.1624,  0.4793],
         [ 0.9823, -1.1624,  0.4793],
         [ 0.9823, -1.1624,  0.4793],
         [ 0.9823, -1.1624,  0.4793]], grad_fn=<SelectBackward0>),
 tensor([[  3571.9363,  21079.5410, -16163.0361],
         [  3571.9363,  21079.5410, -16163.0361],
         [  3571.9363,  21079.5410, -16163.0361],
         [  3571.9363,  21079.5410, -16163.0361],
         [  3571.9363,  21079.5410, -16163.0361]], grad_fn=<SelectBackward0>),
 tensor([[0.0316, 0

In [6]:
outs_1

[tensor([[ 1340.2111,  2556.3630,  4521.8965],
         [ 3721.9065, -4760.1934,  2429.8782],
         [-1549.8695,  1212.5052, -2824.4395],
         [ 1621.1636, -4510.5312,  4276.4038],
         [-5775.6055, -3958.2344,  4413.8530]], grad_fn=<SelectBackward0>),
 tensor([[ 0.0457, -0.0499, -0.0106],
         [ 0.0457, -0.0499, -0.0106],
         [ 0.0457, -0.0499, -0.0106],
         [ 0.0457, -0.0499, -0.0106],
         [ 0.0457, -0.0499, -0.0106]], grad_fn=<SelectBackward0>),
 tensor([[ 0.9823, -1.1624,  0.4793],
         [ 0.9823, -1.1624,  0.4793],
         [ 0.9823, -1.1624,  0.4793],
         [ 0.9823, -1.1624,  0.4793],
         [ 0.9823, -1.1624,  0.4793]], grad_fn=<SelectBackward0>),
 tensor([[  3571.9363,  21079.5410, -16163.0361],
         [  3571.9363,  21079.5410, -16163.0361],
         [  3571.9363,  21079.5410, -16163.0361],
         [  3571.9363,  21079.5410, -16163.0361],
         [  3571.9363,  21079.5410, -16163.0361]], grad_fn=<SelectBackward0>),
 tensor([[0.0316, 0

In [7]:
outs_0[0].dtype

torch.float32

In [8]:
models[0]

INR(
  (net): Sequential(
    (0): ComplexGaborLayer(
      (linear): Linear(in_features=2, out_features=256, bias=True)
    )
    (1): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (2): Linear(in_features=256, out_features=3, bias=True)
  )
)

In [9]:
models[3]

INR(
  (net): Sequential(
    (0): ComplexGaborLayer(
      (linear): Linear(in_features=2, out_features=256, bias=True)
    )
    (1): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (2): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (3): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (4): ComplexGaborLayer(
      (linear): Linear(in_features=256, out_features=256, bias=True)
    )
    (5): Linear(in_features=256, out_features=3, bias=True)
  )
)

In [10]:
layers = list(models[-1].net)

In [11]:
h = inputs_0
outs = [h]
for layer in layers:
    h = layer(h)
    print(h.norm(dim=-1))
    outs.append(h)

tensor([10.0034,  9.9645,  9.5427, 10.0450, 10.1386], grad_fn=<NormBackward1>)
tensor([ 71258.8750,  21037.5586,  90378.9375, 105020.7188,  60026.7344],
       grad_fn=<NormBackward1>)
tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>)
tensor([20.2642, 20.2642, 20.2642, 20.2642, 20.2642], grad_fn=<NormBackward1>)
tensor([1908945.1250, 1908945.1250, 1908945.1250, 1908945.1250, 1908945.1250],
       grad_fn=<NormBackward1>)
tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>)
tensor([21.5672, 21.5672, 21.5672, 21.5672, 21.5672], grad_fn=<NormBackward1>)
tensor([1.3468, 1.3468, 1.3468, 1.3468, 1.3468], grad_fn=<NormBackward1>)


In [12]:
outs[3]

tensor([[0.-0.j, 0.-0.j, 0.-0.j,  ..., 0.+0.j, -0.+0.j, 0.+0.j],
        [-0.-0.j, -0.-0.j, 0.+0.j,  ..., -0.+0.j, -0.-0.j, 0.-0.j],
        [-0.-0.j, -0.-0.j, 0.+0.j,  ..., 0.+0.j, -0.-0.j, -0.-0.j],
        [0.-0.j, 0.-0.j, -0.-0.j,  ..., -0.-0.j, 0.+0.j, -0.+0.j],
        [-0.+0.j, 0.+0.j, -0.-0.j,  ..., -0.-0.j, -0.+0.j, -0.-0.j]],
       grad_fn=<ExpBackward0>)

In [13]:
layers[2](outs[2])

tensor([[0.-0.j, 0.-0.j, 0.-0.j,  ..., 0.+0.j, -0.+0.j, 0.+0.j],
        [-0.-0.j, -0.-0.j, 0.+0.j,  ..., -0.+0.j, -0.-0.j, 0.-0.j],
        [-0.-0.j, -0.-0.j, 0.+0.j,  ..., 0.+0.j, -0.-0.j, -0.-0.j],
        [0.-0.j, 0.-0.j, -0.-0.j,  ..., -0.-0.j, 0.+0.j, -0.+0.j],
        [-0.+0.j, 0.+0.j, -0.-0.j,  ..., -0.-0.j, -0.+0.j, -0.-0.j]],
       grad_fn=<ExpBackward0>)

In [14]:
layers[2].linear.weight

Parameter containing:
tensor([[ 0.0443+0.0532j, -0.0329-0.0464j, -0.0068-0.0499j,  ...,
          0.0252-0.0525j,  0.0192+0.0211j,  0.0606-0.0087j],
        [-0.0100-0.0042j,  0.0507-0.0014j,  0.0608+0.0499j,  ...,
          0.0599-0.0027j,  0.0461+0.0451j, -0.0285+0.0244j],
        [-0.0472+0.0606j, -0.0558-0.0077j, -0.0243-0.0578j,  ...,
          0.0474+0.0491j,  0.0029+0.0623j,  0.0151+0.0392j],
        ...,
        [ 0.0069+0.0463j, -0.0353+0.0094j,  0.0312-0.0186j,  ...,
          0.0452-0.0237j,  0.0157+0.0131j, -0.0537-0.0229j],
        [-0.0400-0.0466j,  0.0160-0.0470j,  0.0249-0.0349j,  ...,
         -0.0354+0.0126j, -0.0545-0.0494j,  0.0493+0.0028j],
        [ 0.0546-0.0523j,  0.0112-0.0438j, -0.0052-0.0133j,  ...,
         -0.0011-0.0516j, -0.0613-0.0045j,  0.0413+0.0075j]],
       requires_grad=True)

In [19]:
pre_activation = outs[2]@layers[2].linear.weight.T + layers[2].linear.bias
pre_activation.real.norm(dim=-1), pre_activation.imag.norm(dim=-1)

(tensor([44928.6992, 11770.3604, 53376.3633, 61112.8125, 33501.7344],
        grad_fn=<NormBackward1>),
 tensor([44238.4727, 12453.2891, 49002.2383, 56772.5820, 33317.7852],
        grad_fn=<NormBackward1>))

In [21]:
freq = 1j * layers[2].omega_0*pre_activation
print(freq.real.norm(dim=-1), freq.imag.norm(dim=-1))
freq = torch.exp(freq)
print(freq.real.norm(dim=-1), freq.imag.norm(dim=-1))

tensor([663577.1875, 186799.2969, 735033.3750, 851588.7500, 499766.7500],
       grad_fn=<NormBackward1>) tensor([673930.3750, 176555.4375, 800645.5000, 916692.3750, 502526.0625],
       grad_fn=<NormBackward1>)
tensor([inf, inf, inf, inf, inf], grad_fn=<NormBackward1>) tensor([inf, inf, inf, inf, inf], grad_fn=<NormBackward1>)


In [23]:
gauss = layers[2].scale_0*pre_activation
print(gauss.real.norm(dim=-1), gauss.imag.norm(dim=-1))
gauss = torch.exp(-torch.square(torch.abs(gauss)))
print(gauss.norm(dim=-1))

tensor([ 89857.3984,  23540.7207, 106752.7266, 122225.6250,  67003.4688],
       grad_fn=<NormBackward1>) tensor([ 88476.9453,  24906.5781,  98004.4766, 113545.1641,  66635.5703],
       grad_fn=<NormBackward1>)
tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>)


In [24]:
gauss * freq

tensor([[nan+nanj, nan+nanj, nan+nanj,  ..., nan+nanj, -0.+0.j, nan+nanj],
        [0.-0.j, 0.-0.j, 0.+0.j,  ..., -0.+0.j, 0.-0.j, nan+nanj],
        [0.-0.j, 0.-0.j, nan+nanj,  ..., 0.+0.j, 0.-0.j, nan+nanj],
        [nan+nanj, nan+nanj, nan+nanj,  ..., 0.-0.j, 0.+0.j, nan+nanj],
        [nan+nanj, 0.+0.j, 0.-0.j,  ..., nan+nanj, nan+nanj, 0.-0.j]],
       grad_fn=<MulBackward0>)

In [26]:
their_way = 1j * layers[2].omega_0*pre_activation - torch.square(torch.abs(layers[2].scale_0*pre_activation))
print(their_way.real.norm(dim=-1), their_way.imag.norm(dim=-1))
their_way = torch.exp(their_way)
print(their_way.real.norm(dim=-1), their_way.imag.norm(dim=-1))

tensor([1.2652e+09, 9.5865e+07, 1.6680e+09, 2.2059e+09, 7.2916e+08],
       grad_fn=<NormBackward1>) tensor([673930.3750, 176555.4375, 800645.5000, 916692.3750, 502526.0625],
       grad_fn=<NormBackward1>)
tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>) tensor([0., 0., 0., 0., 0.], grad_fn=<NormBackward1>)
